### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by bgamari** [well-typed/cborg#115]
As has been pointed out elsewhere, this library has been languishing in a releaseable state for far too long. Here are the current tasks which we are going to push through before the first release,

- [x] Finish the tutorial (#111, @bgamari)
- [x] Finish the encoding stability regression test (#110, @bgamari)
- [x] Rename library to `cborg` (#26, @thoughtpolice or @bgamari)
- [x] Reshuffle module hierarchy to eliminate boot files (#104, @thoughtpolice)
- [ ] Push a release (TBD)

I hope we can get all of these done by mid-next-week.

**Comment by axman6** [comment]
@bgamari, @dcoutts, @thoughtpolice To help make sure this happens, can we set a date this should be completed by? The first of July feels appropriate to me, but is completely arbitrary (the seed for the bike shedding ;))

I feel an incomplete tutorial isn't a huge problem (this can be quickly rectified after release with new point releases), the renaming and module reshuffle should be doable in that time, and relatively painless given the extent of testing (and being Haskell refactoring like this being really mechanical).

**Comment by bgamari** [comment]
I agree that we should set a concrete timeline. Otherwise, as we've seen in the past, things are simply pushed off. July 1 sounds reasonable to me.

I have been working on the tutorial and think that it's pretty close. I am currently working on a patch renaming the library. If @thoughtpolice can't get to it I can possibly reshuffle the module hierarchy, or alternatively we can just punt on it.

**Comment by bgamari** [comment]
At this point there are PRs for all of the above tasks waiting for review. Namely:

 * `cborg` rename (#116)
 * module restructuring (#117)
 * tutorial (#111)

Code review would be greatly appreciated!

**Comment by axman6** [comment]
I was wondering how much closer we are to closing these tickets? IMO all three PRs look ready to go at this point (I made some more comments on the tutorial one but they're not blockers, and improving the tutorial over time is never really going to break anything else so can happen incrementally).

**Comment by bgamari** [comment]
Alright, I think we are there. I'll try to get the necessary credentials to push a release tomorrow.

**Comment by hvr** [comment]
@bgamari you got them already, see https://hackage.haskell.org/package/cborg/maintainers/ :-)

**Comment by bgamari** [comment]
This is currently blocked on https://github.com/haskell/cabal/issues/4629.

**Comment by bgamari** [comment]
It has been done!

Unfortunately I had to disable GHC 7.8 support in the `binary-serialise-cbor` compatibility wrapper. Do let me know whether this is something that you need.
